
Links to data
-------------
[PISA Data](https://www.dropbox.com/s/v0k2joopom6lagj/PISA2003.sav?dl=0)

[PISA Achievement Data](https://www.dropbox.com/s/wz5p7of5q4cnkhi/PISA2003-Achievement.sav?dl=0)

[PISA data for SEM](https://www.dropbox.com/s/q2ctuq74iehm6l9/PISA2003-items.sav?dl=0)


Links to day 2 slides
--------------------
[Regression and multilevel](http://nbviewer.ipython.org/github/pdparker/rcourse/blob/master/Regression%20in%20R.ipynb)

[Structural equation modelling](http://nbviewer.ipython.org/github/pdparker/rcourse/blob/master/SEM.ipynb)

[Missing data via multiple imputations](http://nbviewer.ipython.org/github/pdparker/rcourse/blob/master/Missing%20Data.ipynb)

[Plots](http://nbviewer.ipython.org/github/pdparker/rcourse/blob/master/Plots.ipynb)

Introduction
-------------

Before the course start in the coming weeks I wanted to send some resources your way. We all go through most of this in the course but it is sometimes helpful to get ahead. The outline of the course structure is [below](#structure).


First thing first
------------------

You need to install R.

* For [windows](https://www.youtube.com/watch?v=mfGFv-iB724&feature=youtu.be) watch this video.
* For [mac](https://www.youtube.com/watch?v=Icawuhf0Yqo&feature=youtu.be) watch this video.
* For [linux](https://github.com/swirldev/swirl/wiki/Installing-swirl-on-Linux) check this link as it is not as easy as sudo apt-get.

This will install R on your computer but the graphical user interface is terrible. So we will all be working with [Rstudio](http://www.rstudio.com/). To install go to go [here](http://www.rstudio.com/products/rstudio/#Desk)

For beginners guide to R:

* [Swirl](http://swirlstats.com/) is an interactive tutorial that people rave about. To use it you would do the following. Open R studio and type:

```{r, eval=FALSE}
install.packages("swirl")
library("swirl")
swirl()             
```

* The best book for learning R is [The art of programming in R](http://www.amazon.com/The-Art-Programming-Statistical-Software/dp/1593273843)
* Links for all sorts of R related goodness can be found [here](http://www.talkstats.com/showthread.php/5246-Info-for-R-users-(Links-Manuals-Books-etc.))
* A bunch of courses can be found [here](https://www.coursera.org/courses?categories=stats) but I would recommend working through [this](https://www.coursera.org/specialization/jhudatascience/1?utm_medium=listingPage) for a comprehensive understanding of all things R.
* [This](https://github.com/vhf/free-programming-books/blob/master/free-programming-books.md#r) list of books.

HELP!!!!!!!!!!!!
---------------

Where to go to get help? Before listing resources you need to know how to ask good questions (not as easy as it sounds). [Here](http://www.talkstats.com/showthread.php/14960-Forum-Guidelines-Smart-posting-behavior-pays-off) is a good overview. Remember R is free and community resourced meaning NO ONE is paid to help you (or to be nice to you for that matter). If you show effort you will get amazing support if you are lazy you are likely to be yelled at.

These are the places to go listed in order of nicest to meanest:

* [Talk Stats](http://www.talkstats.com/) is the best place for all things statistics and R
* [Stack overflow](https://stackoverflow.com/questions/tagged/r) for more advanced users
* [Cross validate](https://stats.stackexchange.com/) for all things statistical
* ...
* [R mailing list](https://stat.ethz.ch/mailman/listinfo/r-help) is often manned by the folks who help develop R  **but** folks on here can make Gordon Ramsay look like a fluffy kitten.

Other Stuff:
-------------

I think everyone should know how to use version control software. The most popular is [Git](https://en.wikipedia.org/wiki/Git_%28software%29) which is built into Rstudio. Personally I use [github](https://github.com/). I will not be covering this but it is worth knowing. The course will have a github repo which will have all the course material ready for you to download.

Regards,

Phil

P.S. This webpage was written and compiler in R. We will not cover it but R can produce word documents, PDFs, webpages, interactive webpages, and powerpoint presentations.  

Installation
=================
All lecture notes can be downloaded using the Download ZIP file to the right. I have not included data, pdf, or html files to keep the total file size small. However instructions for downloading and in the exercise files. To create slides you can open the .Rmd files in Rstudio and click the knit button. For those with coding experience and using a Unix system (mac or linux) navigate to the exercise and lecture directories in the **terminal** and type make (see below). For the lecture slides you will need the very awesome [pandoc](http://johnmacfarlane.net/pandoc/) installed. 

```
$ cd /exercises
$ make
$ make clean
```

multiple clean options are available, see the makefile for options.

Example R code
====================

Feel free to check out of [github account](https://github.com/pdparker), [gist account](https://gist.github.com/pdparker), or [blinded for review website](https://github.com/blindedforreview) for my current projects. 


Course Structure
=========================
<a name="structure"></a>


Day 1:
-------------
Part  1 -  Getting Started

* Installing and initial introduction to R and Rstudio
* What forms does data take in R?
* Installing packages
* Getting your data into and out of R
* Creating and using toy data
* Getting help and asking good questions
 
Part 2 - Where is my data?!

* Slicing, dicing, and splitting data?
* Basic descriptives
* Merging and aggregating
* Manipulating and managing
 
Day 2:
------------------
Part 1 - Cleaning

* Looking inside - names, dimensions, types, structures
* Summarizing data
* Recoding
* Write your own functions
* Missing data 
 
Part 2 - Exploring and Modelling Data

* Plotting data - The basics
* The psych package - Never reverse code again!
* Regression, correlations, etc.
* Modelling data - Quick overviews of critical packages
  * lme4 - Multilevel models made simple
  * lavaan - SEM that's cheaper than Mplus
  * survey - weights and multiple imputations
  * ggplot - grammar of graphs