#### Exersises taken from Project Euler projecteuler.net ###


# Problem 1 # 
	# If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.
	# The sum of these multiples is 23.
	#Find the sum of all the multiples of 3 or 5 below 1000.


# Problem  2 # 
	# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
	# By starting with 1 and 2, the first 10 terms will be:
									# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
	# find the sum of the even-valued terms.


# Problem 3 # 
	# The sum of the squares of the first ten natural numbers is,
				# 12 + 22 + ... + 102 = 385
	# The square of the sum of the first ten natural numbers is,
				# (1 + 2 + ... + 10)2 = 552 = 3025
	# Hence the difference between the sum of the squares of the first ten natural numbers
		# and the square of the sum is 3025 − 385 = 2640.
	# Find the difference between the sum of the squares of the first one hundred natural numbers 
		# and the square of the sum.

# Problem 4 #
	# If the numbers 1 to 5 are written out in words: 
		#	one, two, three, four, five, then there are 3 + 3 + 5 + 4 + 4 = 19 letters used in total.
	# If all the numbers from 1 to 1000 (one thousand) inclusive were written out in words, 
		# how many letters would be used?

# Problem 5 #
	# Build a rock,paper scissors, lizard, spock game in R.
	# My python version of the game can be found https://gist.github.com/pdparker/9910919.


# Select problems from Project Euler and post your answers #
	# Sign up for github and save them as gists